# Generated by Django 3.2.4 on 2021-06-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacto',
            new_name='usercontact',
        ),
    ]
